export const recipeCategories = [
  'Grilled',
  'Eggs',
  'Jelly',
  'Ice Cream',
  'Mixed Greens',
  'Bacon-Wrapped',
  'Chocolate',
  'Muffins',
  'Cheesecake',
  'Cake',
  'Gluten-Free',
  'Coconut',
  'Fudge',
  'Filipino',
  'Roasted',
  'Breakfast',
  'Pandan',
  'Pan-Fried',
  'Pan-Seared',
  'Chicken',
  'Salad',
  'Salmon',
  'Cauliflower',
  'Steamed',
  'Seafood',
] as const;

export type RecipeCategory = (typeof recipeCategories)[number];
